package com.vosseptum;

/**
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be
 * 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 */
class DivisibleTriangularNumber
{
    long currentTriangularNumber = 0L;
    private void increaseAndDivideTriangularNumber()
    {
        for(int i = 1; i < 1000000; i++)
        {
            currentTriangularNumber += i;
            if(testForNumberOfDivider(currentTriangularNumber, 500))
            {
                System.out.println(currentTriangularNumber);
                break;
            }
        }
    }

    private boolean testForNumberOfDivider(long numberToTest, int neededDividers)
    {
        int dividers = 0;
        for(int i = 1; i <= Math.sqrt(numberToTest); i++)
        {
            if(numberToTest % i == 0)
            {
                dividers += 2;
            }
        }
        return dividers >= neededDividers;
    }

    DivisibleTriangularNumber()
    {
        increaseAndDivideTriangularNumber();
    }
}
