package com.vosseptum;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
class EvenFibonacciNumbers
{
    private long sumOfEvenFibonaccis = 0;
    private void fibonacciSequence()
    {
        long oldFibonacciNumber = 1;
        long newFibonacciNumber = 1;
        while(newFibonacciNumber <= 4000000)
        {
            newFibonacciNumber = oldFibonacciNumber + newFibonacciNumber;
            oldFibonacciNumber = newFibonacciNumber - oldFibonacciNumber;
            if(newFibonacciNumber % 2 == 0)
            {
                sumOfEvenFibonaccis += newFibonacciNumber;
            }
        }
    }

    EvenFibonacciNumbers()
    {
        fibonacciSequence();
        System.out.print(sumOfEvenFibonaccis);
    }
}
